name: ci

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gyp:
    strategy:
      matrix:
        os: 
        - macos-15
        - ubuntu-24.04
        - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Use Node version defined in manifest
        uses: volta-cli/action@v4.2.1
      - name: Node.js version
        run: node -v
      - name: npm version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Rebuild Node addons
        run: npm run gyp
      - name: Run selenium test suite
        run: npm t
