name: ci

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gyp:
    strategy:
      matrix:
        os: 
        - macos-15
        - ubuntu-24.04
        - windows-2025
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set msvs_version for Windows
        if: runner.os == 'Windows'
        run: echo "msvs_version=2022" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Use Node version defined in manifest
        uses: volta-cli/action@v4.2.1
      - name: Install node-gyp globally
        run: npm install -g node-gyp
      - name: Install dependencies
        run: npm ci
      - name: Run selenium test suite
        run: npm t
